server:
   servlet.context-path: /pf4j_demo
   port: 8082
   max-http-header-size: 2MB
   tomcat.max-http-post-size: 50MB

spring:
  servlet:
      multipart:
         max-file-size: 100MB
         max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


# Redis数据库索引（默认为0）
  redis:
     database: 0
     timeout: 5000  #连接超时时间（毫秒）
     host: 127.0.0.1  #Redis服务器地址
     port: 6379  #Redis服务器连接端口
     jedis:
        pool:
           max-active: 8  #连接池最大连接数（使用负值表示没有限制）
           max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
           max-idle: 8   #连接池中的最大空闲连接
           min-idle: 0   #连接池中的最小空闲连接

  sbp:
#    runtime-mode: development
    runtime-mode: deployment
    enabled: true
#    custom-plugin-loaders: #自定义插件加载
#      - com.kiylx.sbp.demo.CustomPluginLoader
    classes-directories:
      - "target/classes"
      - "out/production/classes"
      - "out/production/resources"
      - "build/classes/java/main"
      - "build/resources/main"
    lib-directories:
      - "libs"
#    plugin-profiles:
#      - share_jta
    plugin-properties:
      spring:
        jpa:
          properties:
            hibernate:
              temp:
                use_jdbc_metadata_defaults: false
          database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    controller:
      base-path: sbp  #很重要，这个指定了controller类的文件路径